USE MASTER 
GO

IF DB_ID('DB_GESTOR_NOTAS') IS NOT NULL
BEGIN
	DROP DATABASE DB_GESTOR_NOTAS
END
GO

CREATE DATABASE DB_GESTOR_NOTAS
GO

USE DB_GESTOR_NOTAS
GO

CREATE TABLE TB_USUARIO(
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_USUARIO VARCHAR(50) NOT NULL,
	APELLIDO_USUARIO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL,
	CONTRASENIA NVARCHAR(255) NOT NULL,
	ROL CHAR(1) CHECK (ROL IN ('P', 'E', 'A')),
	FLGELIMINADO BIT DEFAULT 1
)
GO

CREATE TABLE TB_GRADOS (
    ID_GRADO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_GRADO VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE TB_CURSOS(
	ID_CURSO CHAR(7) PRIMARY KEY,
	NOMBRE_CURSO VARCHAR(50) NOT NULL,
	ID_PROFESOR INT NOT NULL,
	ID_GRADO INT NOT NULL,
	FOREIGN KEY (ID_PROFESOR) REFERENCES TB_USUARIO(ID_USUARIO),
	FOREIGN KEY (ID_GRADO) REFERENCES TB_GRADOS(ID_GRADO)
)
GO

CREATE TABLE TB_ESTUDIANTES_CURSOS(
	ID_CURSO CHAR(7) NOT NULL,
	ID_USUARIO INT NOT NULL,
	PRIMARY KEY (ID_CURSO, ID_USUARIO),
	FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO),
	FOREIGN KEY (ID_CURSO) REFERENCES TB_CURSOS (ID_CURSO)
)
GO

CREATE TABLE TB_NOTAS (
    ID_NOTA INT IDENTITY(1,1) PRIMARY KEY,
    ID_CURSO CHAR(7) NOT NULL,
    ID_USUARIO INT NOT NULL,
    CALIFICACION DECIMAL(5,2) NOT NULL,
    COMENTARIO VARCHAR(255),
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_CURSO) REFERENCES TB_CURSOS(ID_CURSO),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
)

